version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    groups:
      all:
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all:
        update-types:
          - "minor"
          - "patch"
