// Code generated by "stringer -type=LifecycleStage -linecomment"; DO NOT EDIT.

package app

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LifecycleStageCode-1]
	_ = x[LifecycleStageBuild-2]
	_ = x[LifecycleStageTest-3]
	_ = x[LifecycleStageRelease-4]
	_ = x[LifecycleStageDeploy-5]
	_ = x[LifecycleStageOperate-6]
	_ = x[LifecycleStageMonitor-7]
	_ = x[LifecycleStageOther-8]
}

const _LifecycleStage_name = "codebuildtestreleasedeployoperatemonitorother"

var _LifecycleStage_index = [...]uint8{0, 4, 9, 13, 20, 26, 33, 40, 45}

func (i LifecycleStage) String() string {
	i -= 1
	if i < 0 || i >= LifecycleStage(len(_LifecycleStage_index)-1) {
		return "LifecycleStage(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _LifecycleStage_name[_LifecycleStage_index[i]:_LifecycleStage_index[i+1]]
}
