// Code generated by "stringer -type=HealthCheckStatus -linecomment"; DO NOT EDIT.

package app

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HealthCheckStatusUnknown-0]
	_ = x[HealthCheckStatusHealthy-1]
	_ = x[HealthCheckStatusDegraded-2]
	_ = x[HealthCheckStatusDisrupted-3]
}

const _HealthCheckStatus_name = "unknownhealthydegradeddisrupted"

var _HealthCheckStatus_index = [...]uint8{0, 7, 14, 22, 31}

func (i HealthCheckStatus) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_HealthCheckStatus_index)-1 {
		return "HealthCheckStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HealthCheckStatus_name[_HealthCheckStatus_index[idx]:_HealthCheckStatus_index[idx+1]]
}
