name: go-licenses

on: [pull_request]

permissions:
  contents: read

jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Get google/go-licenses package
        run: go install github.com/google/go-licenses@latest
      - name: go-licenses
        run: go-licenses check ${{ github.workspace }}/... --allowed_licenses=Apache-2.0,BSD-3-Clause,BSD-2-Clause,MIT
